FROM python:3.12-slim

WORKDIR /app

COPY requirements-docker.txt .

RUN pip install --no-cache-dir -r requirements-docker.txt

COPY src ./src
COPY api ./api
COPY models/fraud_detection_pipeline.joblib ./models/fraud_detection_pipeline.joblib
COPY models/metadata.json ./models/metadata.json

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
